### ISSUE TITLE
JPA persister does not update state for lazily initialized entities

### ISSUE THREAD

**Issue by hagane** [statefulj/statefulj#16]
Apparently, `JPAPersister` tries to access `@Id` field directly -- but when the entity in question is a Hibernate proxy (enchanced by CGLIB or Javassist), the fields are always null and, actually, they are never used.

EDIT: Upgraded to 2.1, this behaviour is still reproducible.

**Comment by developer-x** [comment]
Can you provide a test case to reproduce this?

I think the right way to address this is to allow annotation of a setter method - but I first want to reproduce the problem as in my hibernate testing - I always used Pojo instead of proxies.

**Comment by hagane** [comment]
Sure, I have some tests in my fork. I'll post a PR in a few minutes.

**Comment by statefulj** [comment]
I've submitted 3.0 to Maven Central.  This includes support for accessing the State property via getter and setter methods.  As a result, it will invoke the proxy which load the Entity into memory.  Your tests are now passing

**Comment by hagane** [comment]
That seems to work. Thanks!
