### ISSUE TITLE
persistence / restoration of state

### ISSUE THREAD

**Issue by lupaelma** [statefulj/statefulj#19]
I would like to save the stateful objects states when my application shuts down and restore them when it comes back up. Is this possible? How would I do it without using persistence to persist every single transition? Thank you!

**Comment by developer-x** [comment]
Statefulj works with the JPA interface to persist the Stateful Entities.  It persists the data with each transition - in fact, it uses the underlying database to ensure each transition is atomic.  Thus there isn't a need to "load up" at the state at startup - it pulls from the database when needed.

If you want, you can use the MemoryPersister to do all transitions but you will need to handle the loading and persisting and startup and shutdown yourself.  You will need to hook into the underlying application framework to do so.  There are many ways to do this depending on which frameworks you're using.  But StatefulJ doesn't offer anything like this out of the box - it's too particular to a person's application to try to develop something general enough that could work for everyone.

**Comment by lupaelma** [comment]
Thanks. It is quite simple to save/restore states from memory but how can I set them into the state machine objects at restore time? Do I have to execute a set of transitions to get the object to the desired state? Is there an easier way? It sounds like it should be easy to set start state of an object but I did not find such API.

Also, it does not seem such a particular request... I see many use cases where storing every single transition is not desirable... e.g. when full recoverability of transitions is not required, when performance could be an issue, etc...

Regards.

**Comment by developer-x** [comment]
StatefulJ acts on Objects that have a state field annotated with the @State annotation.  

If you are going to handle the save/restore yourself - then you simply create a class with a state field and annotate that field with @State annotation.  Then when you load object from the db, create a constructor where you pass in the state value from the db and assign it to the state field - now the object is fully restored to it's previous state.  

If you are using hibernate - hibernate will automatically assign the state value from the database when it loads it from the db.

Either way, when you pass the object into the State Machine, the State Machine will use it's current value for that instance for the transition.  You don't need to execute a set of transitions to get to the desired state.

What StatefulJ does offer is three persister options: Memory, JPA or Mongo.  If you use Memory - which is the default - it will only transition and set the state field on the Entity in memory.  If you choose JPA or Mongo, it will transition and set the value directly in the database - and if successful - set the value in the Entity in memory.  If you use the Memory Persister - it is up to you to decide how to persist and recover the entity (you might be using Elastisearch, Redis, etc...).

**Comment by lupaelma** [comment]
Perfect thank you! I had the impression that persisters were also storing transition information, events, etc... but I understand now that they only change a persisted object state.
