### ISSUE TITLE
Multiple @State annotated properties in class?

### ISSUE THREAD

**Issue by Steve973** [statefulj/statefulj#22]
Hello, @statefulj .  I looked for different avenues of support (mailing list, email, google group, etc) and I apologize if this isn't exactly the right place for this question, but it is the only place that I saw to submit questions, and maybe it will help others that have the same question.

Consider that a domain object can receive state events/updates concerning two different properties.  Let's say that we have a class called AutomobileDriver:

```java
public class AutomobileDriver {
    @State
    String licensed;
    @State
    String insured;

   <other code, etc, here>
}
```

The "licensed" state would have possible values like:
- "NEWYORK_LICENSED"
- "NEWYORK_UNLICENSED"
- etc

The "insured" state would have possible values like:
- "NEWYORK_INSURED_CURRENT"
- "NEWYORK_INSURED_EXPIRED"
- "NEWYORK_UNINSURED"
- etc

If I created states, transitions, actions, a persister, and an FSM instance for each annotated @State property in a class, would the two state properties be managed properly and independently when state events are fired?  If not, how can I manage multiple, but separate, state properties of an object?

**Comment by developer-x** [comment]
StatefulJ only supports a single state per Class since it would be difficult to discern which transition applies to which state field.  In your case, I would reevaluate how you were modeling the AutomobileDriver.  What I'd do is define two additional classes - a LicenseState Class and a InsuranceState Class.  Then apply the Delegation pattern.  So, the AutomobileDriver would delegate the different events to the particular class to handle.  And the AutomobileDriver "getLicensedState" method would delegate to the LicenseState "getState" method whereas the  AutomobileDriver "getInsuranceState" method would delegate to the "LicenseState" class "getState" method.

**Comment by Steve973** [comment]
Thank you.  That worked quite well.

I have another related question: what do the persister implementations actually achieve?  If you only need an in-memory persister, you already have the state in the stateful class.  If you need state over multiple runs, and if you persist your stateful domain object anyway, including the state value, you have the state when the domain object is retrieved from your data store.  So, I am confused about the function of the persister.  Could you shed some light on this, please?

**Comment by developer-x** [comment]
The purpose of the persister is to provide qualified atomic updates to the state.  This is to ensure that transitions handle concurrency.  The memory persister can't synchronize across different instances of a given Domain object or across different servers.  For that, you will need a persister that makes atomic updates in a database.  If you are running a single server and you can guarantee that there won't be multiple versions of an entity updating concurrently, then the memory persister is safe.

Regarding AtomicReference - the memory persister could take advantage of it - but I don't want to require the use of it.  Also, I'm not sure how different ORMs could deal with it.  The difference between the Mongo and JPA Persister is that the Mongo Persister is able to atomically update a state filed within Mongo and JPA Persister can do likewise in a SQL database.  You can use the Persisters even if you are using an ORM to persist the entire Domain object.  The Persister will just update the State only if the value in the DB is equal to the expected state, if it succeeds, it will update the Entity.  If you don't use the Persister, then you should at least employ a versioning strategy on the object to ensure that concurrent writes to the state is caught at the time of saving into the DB.
